### ISSUE TITLE
EXCLUDED by hacktoberfest 2022

### ISSUE THREAD

**Issue by khimji9883** [DipHire/Hacktoberfest2022#71]
<img width="331" alt="Screenshot 2022-10-11 at 11 47 26 PM" src="https://user-images.githubusercontent.com/115577182/195168864-bf40211b-1226-4974-a481-104e51f61925.png">

________________

<div><p>Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation.</p><p>For more information about how exactly we validate PR/MRs for contributors, check the <a href="/participation/#pr-mr-details">details on our participation page</a>.</p></div>

**Comment by DipHire** [comment]
Already updated readme.md 

Thanks 👍
